### PR TITLE
DepoSetSource

### PR DESCRIPTION
**Pull request by HaiwangYu**
Adding new `DepoSetSource`. Passing `DepoSet` instead of queue of `Depos`. Which makes `Pgrapher` engine much more efficient.

### CODE REVIEW

**Comment by knoepfel** [comment]
@HaiwangYu, we are not planning on releasing another version of LArSoft until January.  We hope you're okay with the delay.

**Comment by knoepfel** [comment]
trigger build

**Comment by HaiwangYu** [comment]
> @HaiwangYu, we are not planning on releasing another version of LArSoft until January. We hope you're okay with the delay.

Hi @knoepfel, that is totally OK. Thanks for letting me know. I checked some failed CI tests. Seems not related to this PR. Please let me know if there are some issues that I need to work on.

**Comment by knoepfel** [comment]
Looks good, @HaiwangYu.  Will approve after L2 approval.

**Comment by lgarren** [comment]
trigger build

now that most experiments should be caught up, I hope

**Comment by absolution1** [comment]
It looks like raw pointers declared on the heap are used in a few places.  Is there a specific motivation for that or could those be smart pointers?

**Comment by brettviren** [comment]
> It looks like raw pointers declared on the heap are used in a few places. Is there a specific motivation for that or could those be smart pointers?

The `m_adapter` could be a `unique_ptr`.

This new class is a variant of an existing one so repeats an existing anti-patern.  I propose that fixing these occurrences be done in some dedicated commit.

I will make an issue on this repo to remind us.

**Comment by knoepfel** [comment]
@brettviren, your suggestion sounds good.  Could you reference the issue in this PR when the issue has been created?  In the meantime, we will go ahead and accept the PR, assuming @absolution1 has no other concerns.

**Comment by brettviren** [comment]
It's #14

**Comment by absolution1** [comment]
Great.  Thanks for doing that.
I have no other suggestions/comments.

**Comment by absolution1** [comment]
approve

**Comment by lgarren** [comment]
approve

**Pull request merged**
