### PR TITLE
Spack build of larwirecell build fails at link time because jsoncpp_lib does not exists.

### PR DESCRIPTION
**Pull request by gartung**
jsoncpp_lib is a target not defined somehow.

### CODE REVIEW

**Comment by knoepfel** [comment]
trigger build

**Comment by gartung** [comment]
@knoepfel build fails because it can't find `json/json.h`. Removing `jsoncpp_lib` and/or `jsonnet_lib` (targets?) seemed to cause this.

**Comment by lgarren** [comment]
@gartung I would like some clarification here.  If an expected jsoncpp library is not available, shouldn't we be fixing the spack jsoncpp build?

**Comment by lgarren** [comment]
I'm trying to take a look at this.  `jsoncpp_lib` is a target in the jsoncpp cmake configuration files.   The target corresponds to a `RelWithDebug` build.  How is the spack jsoncpp built?  What targets are generated?

**Comment by gartung** [comment]
There is a patch function in the spack recipe for larwirecell. @knoepfel  asked me to make a pull request for the same change made in the spack recipe. It apparently does not work with the legacy build system.

**Comment by gartung** [comment]
The Spack jsoncpp recipe builds with meson for version >= 1.9.2  so the cmake files are not generated. The meson build only install a pkgconfig file.
` build_system("cmake", conditional("meson", when="@1.9.2:"), default="cmake")`

**Comment by gartung** [comment]
I removed the conditional use of meson on the v0.21.0-fermi branch. I made the same change on v0.22.0-fermi branch so the cmake files should be generated on the next jsoncpp build. I will adjust the larwirecell recipe to remove the patch.

**Pull request closed without merging**
