### PR TITLE
Add one more data product of SimEnergyDeposit to the wire-cell TPC simulation

### PR DESCRIPTION
**Pull request by wenqiang-gu**
There is a request to the protoDUNE simulation task force, which is to save out the TrackIDE with the original XYZ while not the position after SCE distortion. Since the original position information has been wiped out during the SCE simulation, we suggest that the upstream simulation chain can save out two instances of vector<SimEnergyDeposit>. One is with SCE, the other is without SCE. Wire-Cell can read in the two, and make a "link" between them. When it's necessary to save the original XYZ, we can get the initial depo from any corresponding depo after TPC drift simulation.

This PR implements an optional logic for the task above, it should not change any default behavior for any experiment so far.

### CODE REVIEW

**Comment by knoepfel** [comment]
Thanks for the PR, @wenqiang-gu.  There are many things going on here:

- Code that actually addresses the stated issue
- A new module that may be part of addressing the stated issue (difficult to say)
- Some FHiCL file additions

Before accepting this PR, we need some clarification on what code changes are actually necessary to accomplish the goal.  Also, because a new data product is being saved to disk, LArSoft users will want to know what the effect on file sizes and memory will be.  For that reason, we suggest you present your changes at the LArSoft coordination meeting.

Some other things:

- Your FHiCL files introduce dependencies on DUNE and ICARUS, which is not accepted.  Any FHiCL files must be experiment-agnostic as `larwirecell` is used by several experiments.
- You should never include changes to the ups/product_deps file in a PR; those changes will happen as part of the release procedure
- We discourage explicit streaming to `std::cout`.  If you must write informational messages to some logging destination, we encourage you to use `mf::LogInfo` or something similar, which allows users to specify how logging should be done.
- There are many commented-out lines in the new module, the CMakeLists.txt file, and the FHiCL files.  Unless the comments clarify the code, they should be removed as they make it more difficult to grasp what is going on.  In particular, any comments that simply disable old implementation should be removed.

Please let us know when you are able to present at the LArSoft coordination meeting.

**Comment by wenqiang-gu** [comment]
Hi @knoepfel , I can present at the coordination meeting next week. The new module and the FHiCL files are actually useful for adapting the LArSoft wire geometry to fit the WireCell toolkit. It has been in my feature branch for a long time, so I pushed it together. If you think the FHiCL files should not be included, I can just leave a template FHiCL that might be helpful for a beginner from any experiment. 

Anyway, we can discuss the details in the meeting.

**Comment by yangtj207** [comment]
trigger build

**Comment by yangtj207** [comment]
I was not able to trigger build for this PR. Has anyone done it manually?

**Comment by lgarren** [comment]
@yangtj207 triggered in conjunction with larsim PR 39.  We are still working through build problems.

**Comment by lgarren** [comment]
The e19 CI tests are fine.  There was a c7 build problem which is fixed in larwirecell PR 8
https://dbweb5.fnal.gov:8443/LarCI/app/view_builds/index?offset=0&builds=lar_ci/9440&builds=

**Comment by lgarren** [comment]
The history is a little confused due to fixing problems with the bot.  I'm going to approve this for inclusion (with the fix in PR 8).

**Comment by lgarren** [comment]
approve

**Pull request merged**
