### PR TITLE
Update wirecell dependency

### PR DESCRIPTION
**Pull request by gartung**

### CODE REVIEW

**Comment by gartung** [comment]
trigger build with pull requests https://github.com/LArSoft/larwirecell/pull/24

**Comment by gartung** [comment]
trigger build with pull requests #24

**Comment by vitodb** [comment]
trigger build with pull requests #24

**Comment by vitodb** [comment]
trigger build with pull requests #24

**Comment by vitodb** [comment]
trigger build with pull requests #24

**Pull request merged**
